# Generated by Django 4.0.5 on 2022-06-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
