# Generated by Django 4.0.5 on 2022-06-24 09:32

from django.db import migrations, models
import fishare.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_file_file_alter_file_downloads_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.CharField(default=fishare.files.models.slugify, max_length=5),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name='file',
            name='mime_type',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(editable=False, verbose_name='File Size'),
        ),
    ]
