# Generated by Django 4.0.5 on 2022-06-24 09:33

from django.db import migrations, models
import fishare.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.CharField(default=fishare.files.models.slugify, max_length=7, null=None, unique=True),
        ),
    ]
