# Generated by Django 4.0.6 on 2022-07-08 18:34

from django.db import migrations, models
import fishare.files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=models.CharField(default=fishare.files.models.slugify, editable=False, max_length=7, null=None, unique=True),
        ),
    ]
